var MediaAlphaExchange,__maxch__thunk=__maxch__thunk||{};__maxch__thunk.callbacks=__maxch__thunk.callbacks||{};
__maxch__thunk.utils={isFunc:function(b){return"function"===typeof b},captureCallbacks:function(){var b=this,c=__maxch__thunk.callbacks;["click","click_url_preprocessor","error","success"].forEach(function(d){var f;MediaAlphaExchange.callbacks&&b.isFunc(MediaAlphaExchange.callbacks[d])?f=MediaAlphaExchange.callbacks[d]:b.isFunc(MediaAlphaExchange[d])&&(f=MediaAlphaExchange[d]);f&&(c[d]=f);delete MediaAlphaExchange[d]});delete MediaAlphaExchange.callbacks}};
function MediaAlphaExchange__success(b,c,d){function f(a){function e(n){var h=g[n];if(h){var q=h.text||h.textContent||h.innerHTML||"",p=document.getElementsByTagName("head")[0]||document.documentElement,k=document.createElement("script");h=h.getAttribute("src");k.setAttribute("charset","UTF-8");if(h)k.setAttribute("src",h),k.onload=function(){e(n+1)};else{k.setAttribute("type","text/javascript");try{k.appendChild(document.createTextNode(q))}catch(r){k.text=q}}p.insertBefore(k,p.firstChild);p.removeChild(k);
h||e(n+1)}}var g=[];a=a.getElementsByTagName("script");for(var l=0;l<a.length;l++)g.push(a[l]);e(0)}try{var m=document.getElementById(d);m&&(m.innerHTML='<br style="display:none"/>'+c,f(m));"function"===typeof __maxch__thunk.callbacks.success&&__maxch__thunk.callbacks.success(b)}catch(a){}}function MediaAlphaExchange__error(b){try{"function"===typeof __maxch__thunk.callbacks.error&&__maxch__thunk.callbacks.error()}catch(c){}}
function MediaAlphaExchange__click(b,c,d){try{if("function"===typeof __maxch__thunk.callbacks.click_url_preprocessor&&(c=__maxch__thunk.callbacks.click_url_preprocessor(c)),!c)throw Error("Missing Click URL");}catch(f){return console.error(f)}try{"function"===typeof __maxch__thunk.callbacks.click&&__maxch__thunk.callbacks.click(b)}catch(f){}b=navigator.userAgent||navigator.vendor||window.opera;/\[FB(AN|_IAB).*FBAV\/(\d+)/.test(b)&&(d=!0);/Trident/.test(b)?d?window.location.href=c:window.open(c):!d&&
window.open(c)||(window.location.href=c)}
function MediaAlphaExchange__load(b){function c(a,e){switch(typeof a){case "number":a=""+a;case "string":return a.match(/^-\d+$/)?a:a.match(/^\d+$/)?(e?"+":"")+a:a in d?d[a]:"~"+encodeURIComponent(a).replace(/%20/g,"+").replace(/~/g,"%7e")+"~";case "undefined":case "boolean":case "null":return a?1:0;case "object":if(!a)return 0;if("[object Array]"===Object.prototype.toString.apply(a)){var g="[";for(e=0;e<a.length;e++){g+=c(a[e],l);var l=(""+a[e]).match(/^\d+$/)}return g+"]"}g=e?"":"{";for(var n in a)"_design_conf"!=
n&&(l=c(a[n]),void 0!==l&&(g+="~"+encodeURIComponent(n).replace(/%20/g,"+").replace(/~/g,"%7e")+"~"+l));return e?g:g+"}"}}var d={"":"A",first_time_home_buyer:"W",form:"Y",email:"U","7/1 ARM":"vh",Poor:"v4",down_payment:"T",military:"h",phone_2:"m",Condo:"vm",credit_rating:"L",Citibank:"vl",leadid_id:"wS","Single Family Home":"wB",refinance:"vD",coborrower:"J",Modular:"vx",bankruptcy:"G",home_equity:"a",mobile:"i","61-72 months ago":"vg",current_interest_rate:"O",Cooperative:"vn",ad_unit:"E",version:"vM",
current_rate:"R","3-6 months":"va",loan_type:"wM",deposit_term:"wL",Manufactured:"vv",employment_status:"V","Quicken Loans":"v6","12+ months":"vS",additional_cash:"B",points:"p","Not yet removed":"v1","73-84 months ago":"vi",placement_id:"n",address:"C",Townhome:"wC",monthly_debt:"j",Fair:"vr",Employed:"vp",data:"S",zip:"vO",foreclosure:"X",interested_in_home_insurance:"wR",type:"vJ",account_type:"wI",Chase:"vk",credit_score:"wH","Currently in foreclosure":"vo","Wells Fargo":"wF",Other:"v2",income_proof:"c",
"Not Employed":"v0",bank_type:"wJ","49-60 months ago":"vd","Never foreclosed":"vz","30 Year Fixed":"vY",birth_date:"I",phone:"l",deposit_amount:"wK",auto:"F",original_purchase_price:"k","15 Year Fixed":"vU",sub_2:"vH",income:"b",property_type:"s",ua_class:"vK",current_balance:"M",va_loan:"vL",current_lender:"P",Retired:"v8",bankruptcy_removal:"H","3/1 ARM":"vZ","Multi-Family Dwelling":"vy",checking:"wG",purchase_timeframe:"vA",web:"vN","1-12 months ago":"vR","Rental Property":"v7",late_payments:"d",
"1 Year ARM":"vV","40 Year Fixed":"vc",loan_term:"wO",local_hour:"g",car_type:"wP","10 Year Fixed":"vQ",purchase:"u",Mobile:"vw",real_estate_agent:"vC",auto_loan:"wN",home_purchase_status:"wQ",placement_ids:"o",Excellent:"vq","20 Year Fixed":"vW","VA 30 Year":"wE",state:"vF",address_2:"D","Over 84 months ago":"v3",sub_1:"vG","25-36 months ago":"vX","VA 15 Year":"wD",Good:"vu","Bank of America":"vj",sub_3:"vI",property_purchase_year:"r",property_estimated_value:"q","5/1 ARM":"ve",loan_amount:"e","Secondary Home":"v9",
rate_type:"vB",contact:"K",current_mortgage:"Q","37-48 months ago":"vb","0-3 months":"vP",current_home_affordable_refinance_eligible:"N","Primary Home":"v5",found_home:"Z",loan_purpose:"f","6-12 months":"vf","FHA 15 Year":"vs","13-24 months ago":"vT",show_rates:"vE",property_use:"t","Self-Employed":"wA","FHA 30 Year":"vt"};__maxch__thunk.utils.captureCallbacks();MediaAlphaExchange.local_hour=(new Date).getHours();b="//finance.mediaalpha.com/js/serve_.js?z="+c(MediaAlphaExchange,!0)+"&d="+b+"&_="+
Math.floor(1E9*Math.random());var f=document.getElementsByTagName("head").item(0),m=document.createElement("script");m.setAttribute("type","text/javascript");m.setAttribute("src",b);m.setAttribute("charset","UTF-8");f.appendChild(m)}
if("object"==typeof MediaAlphaExchange&&MediaAlphaExchange.placement_id){var targetID="__max__"+Math.floor(1E9*Math.random()),targetElt='<div id="'+targetID+'"></div>';document.currentScript&&"function"===typeof document.currentScript.insertAdjacentHTML?document.currentScript.insertAdjacentHTML("afterend",targetElt):document.write(targetElt);MediaAlphaExchange__load(targetID)};
;
